/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.*;
import connectionmysql.ConnectionMySql;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Esteban
 */
public class EmptyForm extends javax.swing.JFrame {

    private ConnectionMySql conexionMysql;
    private String cedulaAcudiente, codigo;
    private ArrayList <String> datosEstudiante;
    private ArrayList <String> datosAcudiente;
    
    
    public EmptyForm(ConnectionMySql conexionMysql, String cedula, String codigo) {
        this.conexionMysql = conexionMysql;
        this.cedulaAcudiente = cedula;
        this.codigo = codigo;
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        panelEmpleadoUN.setVisible(false);
        panelEmpleado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAño = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox();
        tfTel = new javax.swing.JTextField();
        tfCel = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfEps = new javax.swing.JTextField();
        cbGrupoSang = new javax.swing.JComboBox();
        cbGrado = new javax.swing.JComboBox();
        cbMonto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblGenero = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tfDoc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        panelEmpleadoUN = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cbAreaTrabajo = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        tfExtEmpUN = new javax.swing.JTextField();
        panelEmpleado = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfEmpresa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfTelEmpresa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfDirEmpresa = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfExtension = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bEnviarFormulario = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Grado al que se matricula:");

        jLabel9.setText("EPS:");

        jLabel12.setText("Monto del la matrícula:");

        jLabel3.setText("Nombres:");

        cbAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014" }));

        jLabel10.setText("Grupo sanguíneo:");

        jLabel13.setText("Año:");

        jLabel7.setText("Celular:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Datos Matricula");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfNombre.setName("tfNombre");
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfApellido.setName("tfApellido");
        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        tfTel.setName("tfTel");

        tfCel.setName("tfCel");

        tfDireccion.setName("tfDireccion");
        tfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionActionPerformed(evt);
            }
        });

        tfEps.setName("tfEps");

        cbGrupoSang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AB+", "AB-", "A+", "A-", "B+", "B-", "O+", "O-" }));

        cbGrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jardin", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo", "Noveno", "Décimo", "Once"}));
        cbGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGradoActionPerformed(evt);
            }
        });

        cbMonto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "120000", "150000" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Datos Personales");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Teléfono:");

        jLabel5.setText("Dirección:");

        jLabel4.setText("Apellidos:");

        lblGenero.setText("Género:");

        jLabel28.setText("Número de Documento:");

        tfDoc.setName("tfDoc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(tfApellido))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(tfNombre))
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel13)
                                        .addGap(49, 49, 49)
                                        .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 147, Short.MAX_VALUE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(lblGenero)
                            .addComponent(jLabel28))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDireccion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDoc)
                                    .addComponent(tfEps, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(69, 69, 69)
                                        .addComponent(tfCel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbGrupoSang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(tfDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbGrupoSang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Información del estudiante", jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos Personales");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setText("Nombres:");

        jTextField7.setName("tfNombre");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel16.setText("Apellidos:");

        jTextField8.setName("tfApellido");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel17.setText("Dirección:");

        jTextField9.setName("tfDir");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel18.setText("Teléfono:");

        jTextField10.setName("tfTel");

        jLabel19.setText("Celular:");

        jTextField11.setName("tfCel");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Datos Empleado");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel26.setText("¿Es empleado de la Universidad Nacional?");

        rbSi.setText("Si");
        rbSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSiMouseClicked(evt);
            }
        });
        rbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiActionPerformed(evt);
            }
        });

        rbNo.setText("No");
        rbNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNoMouseClicked(evt);
            }
        });

        panelEmpleadoUN.setName("panelEmpleadoUN");
        panelEmpleadoUN.setBackground(new java.awt.Color(255, 255, 255));
        panelEmpleadoUN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Número de extensión:");
        panelEmpleadoUN.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 58, 172, -1));

        cbAreaTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrativa", "Logistica", "Seguridad", "Biblioteca", "Servicios Varios" }));
        cbAreaTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAreaTrabajoActionPerformed(evt);
            }
        });
        panelEmpleadoUN.add(cbAreaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 11, -1, -1));

        jLabel21.setText("Área de trabajo:");
        panelEmpleadoUN.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 14, 172, -1));
        panelEmpleadoUN.add(tfExtEmpUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 55, 85, -1));

        panelEmpleado.setName("panelEmpleado");
        panelEmpleado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Nombre de la empresa:");

        tfEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmpresaActionPerformed(evt);
            }
        });

        jLabel23.setText("Teléfono de contacto:");

        tfTelEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelEmpresaActionPerformed(evt);
            }
        });

        jLabel24.setText("Dirección:");

        jLabel25.setText("Número de extensión:");

        javax.swing.GroupLayout panelEmpleadoLayout = new javax.swing.GroupLayout(panelEmpleado);
        panelEmpleado.setLayout(panelEmpleadoLayout);
        panelEmpleadoLayout.setHorizontalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(41, 41, 41)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(41, 41, 41)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEmpleadoLayout.setVerticalGroup(
            panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(tfDirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(tfExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 93, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelEmpleadoUN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366)
                        .addComponent(jLabel19)
                        .addGap(50, 50, 50)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel26)
                        .addGap(42, 42, 42)
                        .addComponent(rbSi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(rbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))))
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSi, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addComponent(panelEmpleadoUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jScrollPane2.setViewportView(jPanel3);

        jTabbedPane1.addTab("Información del acudiente", jScrollPane2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Matrícula");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bEnviarFormulario.setText("Enviar Formulario");
        bEnviarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarFormularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEnviarFormulario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEnviarFormulario)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void rbSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSiMouseClicked
        rbNo.setSelected(false);
        panelEmpleado.setVisible(false);
        panelEmpleadoUN.setVisible(true);
    }//GEN-LAST:event_rbSiMouseClicked

    private void cbAreaTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAreaTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAreaTrabajoActionPerformed

    private void rbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiActionPerformed

    }//GEN-LAST:event_rbSiActionPerformed

    private void rbNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNoMouseClicked
        rbSi.setSelected(false);
        panelEmpleadoUN.setVisible(false);
        panelEmpleado.setLocation(panelEmpleadoUN.getLocation());
        panelEmpleado.setVisible(true);
    }//GEN-LAST:event_rbNoMouseClicked

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionActionPerformed

    private void cbGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGradoActionPerformed

    }//GEN-LAST:event_cbGradoActionPerformed

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmpresaActionPerformed

    private void tfTelEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelEmpresaActionPerformed

    private void bEnviarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarFormularioActionPerformed

        Component[] componentsEstudiante = jPanel2.getComponents();//Lista de los componentes del panel con los datos del estudiante
        Component[] componentsAcudiente = jPanel3.getComponents();//Lista de los componentes del panel con los datos del acudiente
        if (checkForm(componentsEstudiante, componentsAcudiente) == false) {
            JOptionPane.showMessageDialog(null, "Imposible enviar el formulario, campos faltantes");
        } else {
            try {
                JOptionPane.showConfirmDialog(null, "¿Esta seguro de enviar el formulario?");
                System.out.println("Inicio de transacción");
                if(insertDatos()){ //Se verifica que la inserción de datos en las tablas haya sido correcta
                    JOptionPane.showMessageDialog(null, "Matricula realizada correctamente");
                    crearReporteMatricula(); //Se crea el reporte de matricula
                    //Realizar el p.a que crea el usuario en la tabla usuario
                    crearUsuario();
                    this.dispose(); //Se cierra la ventana de formulario
                    conexionMysql.con.close();
                    System.exit(0);
                }
            } catch (SQLException ex) {
                try {
                    Logger.getLogger(EmptyForm.class.getName()).log(Level.SEVERE, null, ex);
                    conexionMysql.con.rollback();
                } catch (SQLException ex1) {
                    Logger.getLogger(EmptyForm.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }finally{
                try {
                    conexionMysql.con.setAutoCommit(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EmptyForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
        }
    }//GEN-LAST:event_bEnviarFormularioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviarFormulario;
    private javax.swing.JComboBox cbAreaTrabajo;
    private javax.swing.JComboBox cbAño;
    private javax.swing.JComboBox cbGenero;
    private javax.swing.JComboBox cbGrado;
    private javax.swing.JComboBox cbGrupoSang;
    private javax.swing.JComboBox cbMonto;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JPanel panelEmpleado;
    private javax.swing.JPanel panelEmpleadoUN;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCel;
    private javax.swing.JTextField tfDirEmpresa;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDoc;
    private javax.swing.JTextField tfEmpresa;
    private javax.swing.JTextField tfEps;
    private javax.swing.JTextField tfExtEmpUN;
    private javax.swing.JTextField tfExtension;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTel;
    private javax.swing.JTextField tfTelEmpresa;
    // End of variables declaration//GEN-END:variables

    //Revisa si el formulario esta completo
    public boolean checkForm(Component[] componentsEstudiante, Component[] componentsAcudiente) {
        datosEstudiante = new ArrayList<>();
        datosAcudiente = new ArrayList<>();
        //Revisa los campos del estudiante
        for (int i = 0; i < componentsEstudiante.length; i++) {
            if (componentsEstudiante[i].getClass().getName().toString().equals("javax.swing.JTextField")) {
                JTextField jtf = (JTextField) componentsEstudiante[i];
                datosEstudiante.add(jtf.getText());
                if (jtf.getText().equals("")) {
                    return false;
                }
            }
        }
        //Revisa los datos persnales del acudiente
        for (int i = 0; i < componentsAcudiente.length; i++) {
            if (componentsAcudiente[i].getClass().getName().toString().equals("javax.swing.JTextField")) {
                JTextField jtf = (JTextField) componentsAcudiente[i];
                datosAcudiente.add(jtf.getText());
                if (jtf.getText().equals("")) {
                    return false;
                }
            }
        }
        //Revisa los datos del empleado
        if (!rbSi.isSelected() && !rbNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Elija alguna opcion en el apartado Datos Empleado");
            return false;
        }
        if (rbSi.isSelected()) {
            datosAcudiente.add(tfExtEmpUN.getText());
            return !tfExtEmpUN.getText().equals("");
        }
        if (rbNo.isSelected()) {
            Component[] components = panelEmpleado.getComponents();
            for (int i = 0; i < components.length; i++) {
                if (components[i].getClass().getName().toString().equals("javax.swing.JTextField")) {
                    JTextField jtf = (JTextField) components[i];
                    datosAcudiente.add(jtf.getText());
                    if (jtf.getText().equals("")) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
    
    //Función que inserta los datos del estudiante en la BD
    private boolean insertDatos() throws SQLException {
        try {
            //DATOS ESTUDIANTE
            conexionMysql.con.setAutoCommit(false);
            //Se prepara la sentencia
            PreparedStatement ps = conexionMysql.con.prepareStatement("insert into estudiante (apellido, nombre, direccion, documento, eps, telefono, celular, "
                    + "genero, grupo_sanguineo, monto_matricula, fecha_ingreso, grado, acudiente_matricula) values (?,?,?,?,?,?,?,?,?,?,?,?,?)");
            //Se ingresan los datos al prepated statement
            for (int i =0; i<datosEstudiante.size(); i++){
                ps.setString(i+1, datosEstudiante.get(i));
            }
            ps.setString(8, cbGenero.getSelectedItem().toString());
            ps.setString(9, cbGrupoSang.getSelectedItem().toString());
            ps.setInt(10, Integer.parseInt(cbMonto.getSelectedItem().toString()));
            ps.setString(11, cbAño.getSelectedItem().toString());
            ps.setString(12, cbGrado.getSelectedItem().toString());
            ps.setString(13, cedulaAcudiente);
            //Se ejecuta el prepared statement
            ps.executeUpdate();
            
            //DATOS ACUDIENTE
            if(rbSi.isSelected()){
                //Se prepara la sentencia
                PreparedStatement ps1 = conexionMysql.con.prepareStatement("insert into acudiente (cedula, nombre, apellido, direccion, telefono, celular, extension,"
                    + "area_trabajo) values (?,?,?,?,?,?,?,?)");
                //Se ingresan los datos al prepated statement
                ps1.setString(1, cedulaAcudiente);
                for (int i =0; i<datosAcudiente.size(); i++){
                    ps1.setString(i+2, datosAcudiente.get(i));
                }
                ps1.setString(8, cbAreaTrabajo.getSelectedItem().toString());
                //Se ejecuta el prepared statement
                ps1.executeUpdate(); 
            }
            if(rbNo.isSelected()){
                //Se prepara la sentencia
                PreparedStatement ps2 = conexionMysql.con.prepareStatement("insert into acudiente (cedula, nombre, apellido, direccion, telefono, celular,"
                        + "empresa, telefono_empresa, direccion_empresa, extension) values (?,?,?,?,?,?,?,?,?,?)");
                ps2.setString(1, cedulaAcudiente);
                for (int i = 0; i<datosAcudiente.size(); i++){
                    ps2.setString(i+2, datosAcudiente.get(i));
                }
                //Se ejecuta el prepared statement
                ps2.executeUpdate();
            }
            conexionMysql.con.commit();
            return true;
        } catch (SQLException ex) {
            //Logger.getLogger(EmptyForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error en dato");
            conexionMysql.con.rollback();
            return false;
        }finally{
            conexionMysql.con.setAutoCommit(true);
        }
    }

    public void crearReporteMatricula() {
        try {
            PreparedStatement ps = conexionMysql.con.prepareStatement("insert into reporte_matricula values (?,?,?,?,?)");
            //Se ingresan los datos al prepared statement
            if(codigo.equals("0")){ //Se obtiene el codigo en caso de tratarse de una nueva matricula
                ResultSet rs = conexionMysql.sentencia.executeQuery("select LAST_INSERT_ID()");
                if(rs.next()) codigo = Integer.toString(rs.getInt(1));
            }
            ps.setString(1, codigo);
            ps.setString(2, cedulaAcudiente);
            ps.setString(3, cbAño.getSelectedItem().toString());
            //Se configura la fecha para pasarla como parametro en la insercion
            Date fecha = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            ps.setString(4, sdf.format(fecha)); //Se agrega la fecha
            ps.setString(5, cbGrado.getSelectedItem().toString());
            //Se ejecuta la sentencia
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(EmptyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void crearUsuario() throws SQLException {
        if(codigo.equals("0")){ //Se obtiene el codigo en caso de tratarse de una nueva matricula
                ResultSet rs = conexionMysql.sentencia.executeQuery("select LAST_INSERT_ID()");
                if(rs.next()) codigo = Integer.toString(rs.getInt(1));
        }
        //Se obtiene la informacion para crear el usuario
        ResultSet rs = conexionMysql.sentencia.executeQuery("select nombre, apellido, documento from estudiante where codigo = "
                        + codigo);
        String userName = "";
        String password = "";
        if(rs.next()){
            String [] names = rs.getString(1).split(" ");
            userName += names[0].charAt(0); //Se toma la primera letra del primer nombre
            if(names.length > 1)
                userName += names[1].charAt(0); //Se toma la primera letra del segundo nombre (si tiene)
            String [] lastNames = rs.getString(2).split(" ");
            userName += lastNames[0]; //Se añade el primer apellido
            if(lastNames.length > 1)
                userName += lastNames[1].charAt(0); //Se añade la primera letra del segundo apellido
            password = rs.getString(3); //La contraseña es el documento del estudiante
            CallableStatement cstmt; //Se prepara el llamado al p.a
            //Se preparan las variables
            userName = "\"" + userName + "\"";
            password = "\"" + password+ "\"";
            codigo = "\"" + codigo + "\"";
            //Se prepara la sentencia
            String stmt = "call crear_usuario_estudiante(" + userName + ", " + password + ", " + codigo +  ")";
            cstmt = conexionMysql.con.prepareCall(stmt); //Se prepara la sentencia del p.a
            cstmt.executeUpdate(); //Se ejecuta el p.a
            System.out.println("Ejecutando P.A");
        }
    }
    
    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JButton getbEnviarFormulario() {
        return bEnviarFormulario;
    }

    public ArrayList<String> getDatosEstudiante() {
        return datosEstudiante;
    }

    public ArrayList<String> getDatosAcudiente() {
        return datosAcudiente;
    }

    public JComboBox getCbAreaTrabajo() {
        return cbAreaTrabajo;
    }

    public JComboBox getCbAño() {
        return cbAño;
    }

    public JComboBox getCbGenero() {
        return cbGenero;
    }

    public JComboBox getCbGrado() {
        return cbGrado;
    }

    public JComboBox getCbGrupoSang() {
        return cbGrupoSang;
    }

    public JComboBox getCbMonto() {
        return cbMonto;
    }

    public JRadioButton getRbNo() {
        return rbNo;
    }

    public JRadioButton getRbSi() {
        return rbSi;
    }

    public JPanel getPanelEmpleado() {
        return panelEmpleado;
    }

    public JPanel getPanelEmpleadoUN() {
        return panelEmpleadoUN;
    }

    public JTextField getTfExtEmpUN() {
        return tfExtEmpUN;
    }

    public JTextField getTfDirEmpresa() {
        return tfDirEmpresa;
    }

    public JTextField getTfEmpresa() {
        return tfEmpresa;
    }

    public JTextField getTfExtension() {
        return tfExtension;
    }

    public JTextField getTfTelEmpresa() {
        return tfTelEmpresa;
    }

}
